# SUSE Manager host
host: server.tf.local
user: admin
pass: admin

# Polling interval to contact the SUSE Manager server
# If 0, polling is disabled. Will execute once and exit.
pollinginterval: 60

# Where to write the generated scrape configuration files
outputdir: /etc/prometheus/suma-scrape-config
