# SUSE Manager host
host: server.tf.local
user: admin
pass: admin

# Polling interval to contact the SUSE Manager server
# If 0, polling is disabled. Will execute once and exit.
pollinginterval: 60

# Where to write the generated scrape configuration files
# outputdir: /etc/prometheus/scrape-config/
outputdir: /etc/prometheus/suma-scrape-config


# ----------------------
#    Example rules
# ----------------------

groups:

# Add all clients as scrape targets with job label 'suma'
- labels: { job: suma-systems }
  hosts:
    - match: .*
      ports: [9100]

# More example settings

# # set of base labels that apply to all hosts that match the expressions below
# - labels: { job: ci-server }
#   hosts:
#     # 'match' supports regular expressions
#     - match: jenkins-ci-.* # match all hosts that start with 'jenkins-ci-'
#     # list of ports to be scrapped on hosts that match the expression above
#       ports: [9100] # prometheus node_exporter port
#
# # A more complex example
# - labels: { job: web-servers, environment: production }
#   hosts:
#     - match: proxy-.* # match all hosts that start with 'proxy-'
#       labels: { stack: nginx } # add extra labels to hosts that match the regex above
#       ports: [9100] # scrape port 9100
#       # --
#     - match: apache-.* # match all hosts that start with 'apache-'
#       labels: { stack: apache } # add extra labels to hosts that match the regex above
#       ports: [9100, 9200] # scrape ports 9100 and 9200
#       # --
#       # you can match the same host multiple times if you need to apply specific labels to a scrape port
#       # in this example we want to scrape port 80, with a custom metrics path
#     - match: apache-.*
#       labels: { stack: apache, __metrics_path__: /my-metrics }
#       ports: [80]
